export const EID_SOURCES_BY_MODULE: { [moduleName: string]: string[] } = {
  '33acrossId': ['33across.com'],
  admixerId: ['admixer.net'],
  adplusId: ['ad-plus.com.tr'],
  adtelligent: ['adtelligent.com'],
  amxId: ['amxdt.net'],
  ceeId: ['ceeid.eu'],
  connectId: ['yahoo.com'],
  criteo: ['criteo.com'],
  czechAdId: ['czechadid.cz'],
  dacId: ['impact-ad.jp'],
  deepintentId: ['deepintent.com'],
  euid: ['euid.eu'],
  fabrickId: ['neustar.biz'],
  ftrack: ['flashtalking.com'],
  gemiusId: ['gemius.com'],
  gravitompId: ['gravito.net'],
  growthCodeId: ['growthcode.io'],
  hadronId: ['audigent.com'],
  id5Id: ['id5-sync.com', 'true-link-id5-sync.com'],
  identityLink: ['liveramp.com'],
  idx: ['idx.lat'],
  imuid: ['intimatemerger.com', 'ppid.intimatemerger.com'],
  intentIqId: ['intentiq.com'],
  jixieId: ['jixie.io'],
  justId: ['justtag.com'],
  kpuid: ['kpuid.com'],
  liveIntentId: [
    'bidswitch.net',
    'fpid.liveintent.com',
    'liveintent.com',
    'liveintent.indexexchange.com',
    'liveintent.sonobi.com',
    'liveintent.sovrn.com',
    'liveintent.triplelift.com',
    'liveintent.unrulymedia.com',
    'liveintent.vidazoo.com',
    'media.net',
    'openx.net',
    'pubmatic.com',
    'rubiconproject.com',
    'sharethrough.com',
    'zeta-ssp.liveintent.com',
  ],
  lmpid: ['loblawmedia.ca'],
  lotamePanoramaId: ['crwdcntrl.net'],
  merkleId: ['merkleinc.com'],
  mobkoiId: ['mobkoi.com'],
  mwOpenLinkId: ['mediawallahscript.com'],
  mygaruId: ['mygaru.com'],
  naveggId: ['navegg.com'],
  netId: ['netid.de'],
  novatiq: ['novatiq.com'],
  operaId: ['t.adx.opera.com'],
  pairId: ['google.com'],
  parrableId: ['parrable.com'],
  pubCommonId: ['pubcid.org'],
  publinkId: ['epsilon.com'],
  pubmaticId: ['esp.pubmatic.com'],
  qid: ['adquery.io'],
  sharedId: ['pubcid.org'],
  startioId: ['start.io'],
  taboolaId: ['taboola.com'],
  tapadId: ['tapad.com'],
  teadsId: ['teads.com'],
  tncId: ['thenewco.it'],
  uid2: ['uidapi.com'],
  unifiedId: ['adserver.org'],
  utiqId: ['utiq.com'],
  utiqMtpId: ['utiq-mtp.com'],
  zeotapIdPlus: ['zeotap.com'],
};
