/**
 * Endpoint domains each prebid user id / RTD module calls, used to attribute network requests to the
 * provider that made them.
 *
 * GENERATED - do not edit by hand.
 * Run `node utils/prebidMetadata/extractProviderHosts.mjs` after bumping prebid.js.
 *
 * Keys are `<componentType>:<componentName>`, matching the names used in
 * `realTimeData.dataProviders[].name` and `userSync.userIds[].name`.
 *
 * Documentation links and shared infrastructure (amazonaws, gstatic, doubleclick...) are excluded: a
 * missing attribution is better than a wrong one. Modules whose endpoint comes from publisher config
 * are absent on purpose - those hosts are read from the live config instead.
 */
export const PROVIDER_HOSTS: { [typeAndName: string]: string[] } = {
  'analytics:33across': ['33across.com'],
  'analytics:adagio': ['4dex.io'],
  'analytics:adloox': ['adloox.com', 'adlooxtracking.com'],
  'analytics:adnuntius': ['adnuntius.com'],
  'analytics:adplus': ['ad-plus.com.tr'],
  'analytics:advRed': ['adv.red'],
  'analytics:adWMG': ['wmgroup.us'],
  'analytics:adxpremium': ['adxpremium.services'],
  'analytics:agma': ['agma-analytics.de'],
  'analytics:appierAnalytics': ['appier.net'],
  'analytics:asteriobid': ['asteriobid.com'],
  'analytics:atsAnalytics': ['liveramp.com', 'rlcdn.com'],
  'analytics:browsi': ['browsiprod.com'],
  'analytics:bydata': ['bydata.com'],
  'analytics:concert': ['concert.io'],
  'analytics:datawrkzanalytics': ['highr.ai'],
  'analytics:finteza': ['mql5.com'],
  'analytics:greenbids': ['greenbids.ai'],
  'analytics:growthCodeAnalytics': ['gcprivacy.com'],
  'analytics:hadronAnalytics': ['ad.gt'],
  'analytics:id5Analytics': ['id5-sync.com'],
  'analytics:iiqAnalytics': ['geeksforgeeks.org', 'intentiq.com'],
  'analytics:imAnalytics': ['im-apps.net'],
  'analytics:invisiblyAnalytics': ['pymx5.com'],
  'analytics:kargo': ['kargo.com'],
  'analytics:liveintent': ['liadm.com'],
  'analytics:livewrapped': ['lwadm.com'],
  'analytics:malltv': ['mall.tv'],
  'analytics:medianetAnalytics': ['media.net'],
  'analytics:mobkoi': ['mobkoi.com'],
  'analytics:nobid': ['servenobids.com'],
  'analytics:oolo': ['oolo.io'],
  'analytics:pgamdirect': ['pgammedia.com'],
  'analytics:prebidmanager': ['prebidmanager.com'],
  'analytics:pubmatic': ['pubmatic.com'],
  'analytics:pubperf': ['pubperf.com'],
  'analytics:pubwise': ['pubwise.io'],
  'analytics:scaleable': ['scaleable.ai'],
  'analytics:sharethrough': ['sharethrough.com'],
  'analytics:smartyads': ['ivcsmrt.com'],
  'analytics:symitri': ['windows.net'],
  'analytics:ucfunnelAnalytics': ['aralego.com'],
  'analytics:uniquest': ['ust-ad.com'],
  'analytics:yieldone': ['iponweb.net'],
  'analytics:zeta_global_ssp': ['disqus.com'],
  'bidder:1accord': ['adnxs.com', 'first-id.fr', 'glomex.com', 'iab.com', 'nexx360.io', 'plug.it', 'pubx.ai', 'yieldbird.com'],
  'bidder:33across': ['33across.com', 'iab.com'],
  'bidder:33across_mgni': ['33across.com', 'iab.com'],
  'bidder:360playvid': ['360playvid.com'],
  'bidder:a1media': ['contentsfeed.com', 'iab.com'],
  'bidder:a4g': ['ad4game.com'],
  'bidder:ablida': ['ablida.net'],
  'bidder:aceex': ['aceex.io'],
  'bidder:acuityads': ['acuityads.com', 'admanmedia.com'],
  'bidder:ad2': ['ad2iction.com'],
  'bidder:ad2iction': ['ad2iction.com'],
  'bidder:adagio': ['4dex.io', 'adagio.io', 'bluebillywig.com'],
  'bidder:adasta': ['adnxs-simple.com', 'adnxs.com', 'adzymic.com', 'appnexus.com', 'b-cdn.net', 'linkedin.com', 'npm.im', 'projectagora.net'],
  'bidder:adastra': ['attekmi.co', 'shb-sync.com'],
  'bidder:adbite': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:adblender': ['admixer.com', 'admixer.net', 'futureads.io', 'go2net.com.ua', 'smn.rs'],
  'bidder:adbro': ['adbro.me', 'iab.com'],
  'bidder:adcluster': ['adcluster.com.tr'],
  'bidder:addefend': ['addefend-platform.com', 'addefend.com'],
  'bidder:addigi': ['attekmi.co', 'shb-sync.com'],
  'bidder:adelerate': ['bidelerate.com', 'iab.com'],
  'bidder:adf': ['adform.com', 'adform.net', 'iab.com'],
  'bidder:adform': ['adform.com', 'adform.net', 'iab.com'],
  'bidder:adformOpenRTB': ['adform.com', 'adform.net', 'iab.com'],
  'bidder:adfusion': ['iab.com', 'spicyrtb.com'],
  'bidder:adg': ['apvdr.com', 'iab.com', 'pragmaticwebsecurity.com', 'scaleout.jp', 'socdm.com'],
  'bidder:adgeneration': ['apvdr.com', 'iab.com', 'pragmaticwebsecurity.com', 'scaleout.jp', 'socdm.com'],
  'bidder:adgrid': ['adnxs.com', 'iab.com', 'nexx360.io'],
  'bidder:adhash': ['adhash.com'],
  'bidder:adhese': ['adhese.com'],
  'bidder:adingo': ['adingo.jp'],
  'bidder:adipolo': ['adipolo.com'],
  'bidder:adkernel': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:adkernelAdn': ['adkernel.com'],
  'bidder:adklip': ['adserver.online', 'aso1.net', 'bidgx.com', 'iab.com', 'kuantyx.com'],
  'bidder:adliveplus': ['iab.com'],
  'bidder:adlivetech': ['adnxs.com', 'bidswitch.net', 'themediagrid.com'],
  'bidder:adlywise': ['attekmi.co', 'shb-sync.com'],
  'bidder:admaru': ['admaru.net'],
  'bidder:admatic': ['admatic.com.tr', 'admatic.de', 'adnxs.com', 'adtarget.com.tr'],
  'bidder:admaticde': ['admatic.com.tr', 'admatic.de', 'adnxs.com', 'adtarget.com.tr'],
  'bidder:admedia': ['admedia.com'],
  'bidder:admixer': ['admixer.com', 'admixer.net', 'futureads.io', 'go2net.com.ua', 'smn.rs'],
  'bidder:admixeradx': ['admixer.com', 'admixer.net', 'futureads.io', 'go2net.com.ua', 'smn.rs'],
  'bidder:adndeal1': ['adnuntius.com'],
  'bidder:adndeal2': ['adnuntius.com'],
  'bidder:adndeal3': ['adnuntius.com'],
  'bidder:adndeal4': ['adnuntius.com'],
  'bidder:adndeal5': ['adnuntius.com'],
  'bidder:adnex': ['attekmi.co', 'shb-sync.com'],
  'bidder:adnimation': ['adnimation.com', 'cootlogix.com', 'npm.im'],
  'bidder:adnow': ['nnowa.com'],
  'bidder:adnuntius': ['adnuntius.com'],
  'bidder:adocean': ['gemius.com'],
  'bidder:adot': ['adotmob.com'],
  'bidder:adplus': ['ad-plus.com.tr'],
  'bidder:adpluto': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:adpluto_dsp': ['adkernel.com'],
  'bidder:adpone': ['adpone.com'],
  'bidder:adport': ['iab.com'],
  'bidder:adprime': ['adprime.com'],
  'bidder:adquery': ['adquery.io'],
  'bidder:adr': ['adrelevantis.com', 'npm.im'],
  'bidder:adrelevantis': ['adrelevantis.com', 'npm.im'],
  'bidder:adrino': ['adrino.cloud', 'adrino.io'],
  'bidder:adriver': ['adriver.ru'],
  'bidder:adrubi': ['admatic.com.tr', 'admatic.de', 'adnxs.com', 'adtarget.com.tr'],
  'bidder:ads_interactive': ['adsinteractive.com'],
  'bidder:adsinteractive': ['adsinteractive.com'],
  'bidder:adsmart': ['adrelevantis.com', 'npm.im'],
  'bidder:adsmovil': ['adsmovil.com'],
  'bidder:adsolut': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:adstir': ['ad-stir.com'],
  'bidder:adsyield': ['iab.com', 'iion.io', 'orangeclickmedia.com'],
  'bidder:adt': ['admatic.com.tr', 'admatic.de', 'adnxs.com', 'adtarget.com.tr'],
  'bidder:adtarget': ['adtarget.com.tr', 'npm.im'],
  'bidder:adtelligent': ['adtelligent.com', 'npm.im'],
  'bidder:adtg_org': ['iab.com', 'iion.io', 'orangeclickmedia.com'],
  'bidder:adtrgtme': ['adtarget.market', 'iab.com'],
  'bidder:adtrue': ['adtrue.com'],
  'bidder:aduptech': ['adup-tech.com'],
  'bidder:advangelists': ['advangelists.com', 'beachfrontmedia.com'],
  'bidder:advertising': ['technoratimedia.com'],
  'bidder:adverxo': ['iab.com'],
  'bidder:adwebone': ['adnxs.com', 'first-id.fr', 'glomex.com', 'iab.com', 'nexx360.io', 'plug.it', 'pubx.ai', 'yieldbird.com'],
  'bidder:adWMG': ['adwmg.com'],
  'bidder:adxcg': ['adxcg.net', 'iab.com'],
  'bidder:adyoulike': ['adyoulike.com', 'omnitagjs.com'],
  'bidder:adzymic': ['adnxs-simple.com', 'adnxs.com', 'adzymic.com', 'appnexus.com', 'b-cdn.net', 'linkedin.com', 'npm.im', 'projectagora.net'],
  'bidder:afp': ['afp.ai', 'rtbinsight.ru'],
  'bidder:agenticx': ['adsmartx.com', 'iab.com', 'theagenticx.ai'],
  'bidder:aidem': ['aidemsrv.com', 'iab.com'],
  'bidder:aja': ['adtdp.com'],
  'bidder:akcelo': ['iab.com', 'sportslocalmedia.com'],
  'bidder:alchemyx': ['iab.com'],
  'bidder:algorix': ['algorix.co', 'iab.com'],
  'bidder:alkimi': ['alkimi-onboarding.com'],
  'bidder:allegro': ['allegro.pl', 'allegrostatic.com', 'iab.com'],
  'bidder:alliance_gravity': ['adnxs.com', 'agrvt.com', 'alliancegravity.com', 'iab.com'],
  'bidder:altstar': ['iab.com', 'iion.io', 'orangeclickmedia.com'],
  'bidder:alvads': ['ssidevops.com'],
  'bidder:amcom': ['attekmi.co', 'shb-sync.com'],
  'bidder:amx': ['a-mo.net'],
  'bidder:aniview': ['aniview.com', 'iab.com'],
  'bidder:anyclip': ['anyclip.com'],
  'bidder:anzu': ['attekmi.co', 'shb-sync.com'],
  'bidder:anzuDSP': ['anzu-rtb.live'],
  'bidder:anzuExchange': ['iab.com', 'iion.io', 'orangeclickmedia.com'],
  'bidder:anzuSSP': ['anzumarketplace.com'],
  'bidder:aotter': ['aotter.net'],
  'bidder:apacdex': ['quantumdex.io'],
  'bidder:apester': ['apester.com', 'cootlogix.com', 'npm.im'],
  'bidder:appier': ['appier.com'],
  'bidder:appierBR': ['appier.com'],
  'bidder:appierExt': ['appier.com'],
  'bidder:appierGM': ['appier.com'],
  'bidder:appmonsta': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:appMonstaMedia': ['appmonsta.ai'],
  'bidder:appnexus': ['adnxs-simple.com', 'adnxs.com', 'adzymic.com', 'appnexus.com', 'b-cdn.net', 'linkedin.com', 'npm.im', 'projectagora.net'],
  'bidder:appnexusAst': ['adnxs-simple.com', 'adnxs.com', 'adzymic.com', 'appnexus.com', 'b-cdn.net', 'linkedin.com', 'npm.im', 'projectagora.net'],
  'bidder:appStockSSP': ['al-ad.com', 'app-stock.com'],
  'bidder:appush': ['appush.com', 'thebiding.com'],
  'bidder:aps': ['amazon-adsystem.com', 'iab.com', 'media-amazon.com'],
  'bidder:apstream': ['userreport.com'],
  'bidder:artechnology': ['attekmi.co', 'shb-sync.com'],
  'bidder:aseal': ['aotter.net'],
  'bidder:aso': ['adserver.online', 'aso1.net', 'bidgx.com', 'iab.com', 'kuantyx.com'],
  'bidder:asterio': ['asterio.ai'],
  'bidder:astraone': ['astraone.io'],
  'bidder:atd': ['atmtd.com'],
  'bidder:attekmi': ['attekmi.co', 'shb-sync.com'],
  'bidder:audiencemedia': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:audiencerun': ['audiencerun.com'],
  'bidder:automatad': ['atmtd.com'],
  'bidder:avantisvideo': ['aniview.com', 'iab.com'],
  'bidder:axis': ['axis-marketplace.com'],
  'bidder:axonix': ['axonix.com'],
  'bidder:ayl': ['adyoulike.com', 'omnitagjs.com'],
  'bidder:bcm': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:bcmint': ['adserver.online', 'aso1.net', 'bidgx.com', 'iab.com', 'kuantyx.com'],
  'bidder:bcmssp': ['marphezis.com'],
  'bidder:beachfront': ['beachfrontmedia.com', 'bfmio.com', 'seedtag.com'],
  'bidder:bedigitech': ['bedigitech.com'],
  'bidder:beintoo': ['adnxs-simple.com', 'adnxs.com', 'adzymic.com', 'appnexus.com', 'b-cdn.net', 'linkedin.com', 'npm.im', 'projectagora.net'],
  'bidder:beop': ['collectiveaudience.co', 'mongodb.com'],
  'bidder:between': ['adnxs.com', 'betweendigital.com', 'betweenx.com'],
  'bidder:beyondmedia': ['andbeyond.media'],
  'bidder:bg': ['bid.glass'],
  'bidder:biddo': ['adopx.net'],
  'bidder:bidfuse': ['bidfuse.com'],
  'bidder:bidgency': ['adserver.online', 'aso1.net', 'bidgx.com', 'iab.com', 'kuantyx.com'],
  'bidder:bidglass': ['bid.glass'],
  'bidder:bidmatic': ['bidmatic.io', 'npm.im'],
  'bidder:bidscube': ['bidscube.com'],
  'bidder:bidsmind': ['iab.com'],
  'bidder:bidstailamedia': ['adnxs.com', 'first-id.fr', 'glomex.com', 'iab.com', 'nexx360.io', 'plug.it', 'pubx.ai', 'yieldbird.com'],
  'bidder:bidtheatre': ['bidtheatre.com', 'iab.com'],
  'bidder:big-richmedia': ['adnxs-simple.com', 'adnxs.com', 'appnexus.com', 'hubvisor.io', 'linkedin.com', 'npm.im'],
  'bidder:billow_rtb25': ['billowlink.com', 'iab.com'],
  'bidder:bitmedia': ['bmcdn7.com', 'iab.com'],
  'bidder:bk': ['bliink.io'],
  'bidder:blasto': ['iab.com'],
  'bidder:bliink': ['bliink.io'],
  'bidder:blockthrough': ['blockthrough.com', 'btloader.com', 'iab.com'],
  'bidder:blue': ['getblue.io', 'iab.com'],
  'bidder:blutonic': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:bms': ['bluems.com', 'iab.com'],
  'bidder:bmtm': ['brightmountainmedia.com', 'elitebidder.com'],
  'bidder:boldwin': ['videowalldirect.com'],
  'bidder:bp': ['collectiveaudience.co', 'mongodb.com'],
  'bidder:brainx': ['brainx.tech', 'iab.com', 'tec-do.cn'],
  'bidder:brave': ['braveglobal.tv'],
  'bidder:brid': ['adnxs.com', 'prebrid.tv', 'target-video.com'],
  'bidder:bridgeupp': ['bridgeupp.com', 'iab.com', 'sonar-ads.com'],
  'bidder:bridgewell': ['scupio.com'],
  'bidder:brightcom': ['marphezis.com'],
  'bidder:brightmountainmedia': ['brightmountainmedia.com', 'elitebidder.com'],
  'bidder:browsi': ['avantisvideo.com', 'browsiprod.com'],
  'bidder:bt': ['blockthrough.com', 'btloader.com', 'iab.com'],
  'bidder:btw': ['adnxs.com', 'betweendigital.com', 'betweenx.com'],
  'bidder:bucksense': ['bksnimages.com', 'prebidserving.com'],
  'bidder:buzzoola': ['buzzoola.com'],
  'bidder:buzzoolaAdapter': ['buzzoola.com'],
  'bidder:c1x': ['c1exchange.com'],
  'bidder:cadent': ['cadent.com'],
  'bidder:cadent_aperture_mx': ['cadent.com'],
  'bidder:cadentaperturemx': ['cadent.com'],
  'bidder:caroda': ['caroda.io'],
  'bidder:ccx': ['clickonometrics.pl'],
  'bidder:chtnw': ['hinet.net'],
  'bidder:cleanmedianet': ['cleanmediaads.com', 'gamoshi.io', 'iab.com'],
  'bidder:clickforce': ['holmesmind.com'],
  'bidder:clickio': ['clickiocdn.com', 'iab.com'],
  'bidder:clmb': ['clmbtech.com'],
  'bidder:clydo': ['iab.com'],
  'bidder:cnvr': ['dotomi.com', 'iab.com'],
  'bidder:codefuel': ['seccint.com'],
  'bidder:cointraffic': ['adsgravity.io'],
  'bidder:coinzilla': ['czilladx.com'],
  'bidder:colombia': ['clmbtech.com'],
  'bidder:colossusssp': ['colossusssp.com'],
  'bidder:compariola': ['adrelevantis.com', 'npm.im'],
  'bidder:compass': ['deliverimp.com', 'marphezis.com'],
  'bidder:conceptx': ['cncpt.dk', 'cncptx.com'],
  'bidder:concert': ['concert.io'],
  'bidder:condorx': ['condorx.io', 'iab.com'],
  'bidder:connatix': ['connatix.com'],
  'bidder:connectad': ['connectad.io', 'iab.com'],
  'bidder:connectadrealtime': ['connectad.io', 'iab.com'],
  'bidder:consumable': ['serverbid.com'],
  'bidder:contentexchange': ['adnetwork.agency', 'contentexchange.me'],
  'bidder:contxtful': ['iab.com'],
  'bidder:converge': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:conversant': ['dotomi.com', 'iab.com'],
  'bidder:copper6ssp': ['cootlogix.com', 'copper6.com', 'npm.im'],
  'bidder:cordless': ['adserver.online', 'aso1.net', 'bidgx.com', 'iab.com', 'kuantyx.com'],
  'bidder:cortex': ['targetadserver.com'],
  'bidder:cpmstar': ['aditude.com', 'cpmstar.com', 'iab.com'],
  'bidder:craft': ['gacraft.jp'],
  'bidder:criteo': ['criteo.com', 'criteo.net', 'iab.com'],
  'bidder:cwire': ['adnxs.com', 'cwi.re'],
  'bidder:czlla': ['czilladx.com'],
  'bidder:dailyhunt': ['dailyhunt.in'],
  'bidder:dailymotion': ['dmcdn.net', 'dmxleo.com', 'iab.com'],
  'bidder:das': ['ocdn.eu', 'onet.pl'],
  'bidder:datafusion': ['iab.com', 'iion.io', 'orangeclickmedia.com'],
  'bidder:datawrkz': ['datawrkz.com'],
  'bidder:deepintent': ['deepintent.com'],
  'bidder:defineMedia': ['conative.network', 'definemedia.de', 'iab.com'],
  'bidder:deltaprojects': ['de17a.com'],
  'bidder:denakop': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:dexerto': ['dexerto.media'],
  'bidder:dh': ['dailyhunt.in'],
  'bidder:dia': ['dianomi.com'],
  'bidder:dianomi': ['dianomi.com'],
  'bidder:dichange': ['digitalmatter.ai', 'digitalmatter.services'],
  'bidder:didnadisplay': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:didnavideo': ['aniview.com', 'iab.com'],
  'bidder:digiad': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:digitalMatter': ['digitalmatter.ai', 'digitalmatter.services'],
  'bidder:digitalmatter': ['digitalmatter.ai', 'digitalmatter.services'],
  'bidder:discovery': ['mediago.io', 'popin.cc'],
  'bidder:displayioads': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:distroscale': ['jsrdn.com'],
  'bidder:djax': ['adnxs.com', 'djaxbidder.com'],
  'bidder:doceree': ['doceree.com'],
  'bidder:docereeadmanager': ['doceree.com'],
  'bidder:dochase': ['dochaseadx.com'],
  'bidder:dpai': ['drift-pixel.ai'],
  'bidder:driftpixel': ['driftpixel.live'],
  'bidder:ds': ['jsrdn.com'],
  'bidder:dsp_geniee': ['gsspat.jp', 'iab.com'],
  'bidder:dspx': ['adtech.app', 'dspx.tv'],
  'bidder:duration': ['nobid.com', 'servenobid.com'],
  'bidder:dvgroup': ['iab.com'],
  'bidder:dxkulture': ['dxkulture.com', 'iab.com'],
  'bidder:dxtech': ['dxtech.ai', 'iab.com'],
  'bidder:e_volution': ['e-volution.ai'],
  'bidder:easybid': ['adnxs.com', 'first-id.fr', 'glomex.com', 'iab.com', 'nexx360.io', 'plug.it', 'pubx.ai', 'yieldbird.com'],
  'bidder:eclick': ['eclick.vn'],
  'bidder:edge226': ['dauup.com', 'serveteck.com'],
  'bidder:ehealthcaresolutions': ['ehealthcaresolutions.com'],
  'bidder:eightpod': ['8pod.com', '8podx.com', 'iab.com'],
  'bidder:embimedia': ['iab.com', 'iion.io', 'orangeclickmedia.com'],
  'bidder:empower': ['empower.net', 'virgul.com'],
  'bidder:emtv': ['engagemedia.tv'],
  'bidder:emx_digital': ['cadent.com'],
  'bidder:emxdigital': ['cadent.com'],
  'bidder:engageadx': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:engagesimply': ['adkernel.com'],
  'bidder:engageya': ['engageya.com'],
  'bidder:engerio': ['engerio.sk'],
  'bidder:epsilon': ['dotomi.com', 'iab.com'],
  'bidder:equativ': ['iab.com', 'sascdn.com', 'smartadserver.com'],
  'bidder:ergadx': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:escalax': ['iab.com'],
  'bidder:eskimi': ['eskimi.com', 'iab.com'],
  'bidder:etarget': ['etarget.sk'],
  'bidder:ex': ['seccint.com'],
  'bidder:exads': ['native7.com'],
  'bidder:exco': ['ex.co', 'iab.com'],
  'bidder:featureforward': ['adnxs-simple.com', 'adnxs.com', 'adzymic.com', 'appnexus.com', 'b-cdn.net', 'linkedin.com', 'npm.im', 'projectagora.net'],
  'bidder:feedad': ['feedad.com'],
  'bidder:felixads': ['attekmi.co', 'shb-sync.com'],
  'bidder:ferio': ['featuretv.bid', 'ferio.bid'],
  'bidder:finative': ['finative.cloud'],
  'bidder:first-id': ['adnxs.com', 'first-id.fr', 'glomex.com', 'iab.com', 'nexx360.io', 'plug.it', 'pubx.ai', 'yieldbird.com'],
  'bidder:flipp': ['ads-flipp.com'],
  'bidder:floxis': ['floxis.tech', 'iab.com'],
  'bidder:fluct': ['adingo.jp'],
  'bidder:freedomadnetwork': ['armanet.us', 'freedomadnetwork.com', 'iab.com'],
  'bidder:freepass': ['ad-m.asia', 'iab.com'],
  'bidder:freewheel-mrm': ['fwmrm.net'],
  'bidder:futureads': ['admixer.com', 'admixer.net', 'futureads.io', 'go2net.com.ua', 'smn.rs'],
  'bidder:fwssp': ['fwmrm.net'],
  'bidder:gambid': ['cleanmediaads.com', 'gamoshi.io', 'iab.com'],
  'bidder:gamma': ['gammaplatform.com'],
  'bidder:gamoshi': ['cleanmediaads.com', 'gamoshi.io', 'iab.com'],
  'bidder:gg': ['gumgum.com'],
  'bidder:gjirafa': ['gjirafa.com'],
  'bidder:global_sun': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:glomex': ['glomex.cloud', 'glomex.com'],
  'bidder:glomexbidder': ['adnxs.com', 'first-id.fr', 'glomex.com', 'iab.com', 'nexx360.io', 'plug.it', 'pubx.ai', 'yieldbird.com'],
  'bidder:gmossp': ['gmossp-sp.jp'],
  'bidder:gnet': ['gnetrtb.com'],
  'bidder:go2net': ['admixer.com', 'admixer.net', 'futureads.io', 'go2net.com.ua', 'smn.rs'],
  'bidder:goadserver': ['iab.com'],
  'bidder:goldbach': ['gb-next.ch', 'gbads.net', 'gbadtech.io', 'iab.com'],
  'bidder:gourmetads': ['adnxs-simple.com', 'adnxs.com', 'adzymic.com', 'appnexus.com', 'b-cdn.net', 'linkedin.com', 'npm.im', 'projectagora.net'],
  'bidder:greenbids': ['greenbids.ai'],
  'bidder:grid': ['adnxs.com', 'bidswitch.net', 'themediagrid.com'],
  'bidder:gridNM': ['adnxs.com', 'bidswitch.net', 'themediagrid.com'],
  'bidder:gumgum': ['gumgum.com'],
  'bidder:h12': ['h12-media.com'],
  'bidder:h12media': ['h12-media.com'],
  'bidder:haloads': ['haloads.io', 'iab.com'],
  'bidder:harion': ['harion-ma.com', 'markappmedia.site'],
  'bidder:harrenmedia': ['iab.com'],
  'bidder:headbidder': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:headbidding': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:holid': ['adform.net', 'holid.io'],
  'bidder:hubvisor': ['hubvisor.io', 'iab.com'],
  'bidder:hybrid': ['adnxs.com', 'hybrid.ai'],
  'bidder:hype': ['hypelab.com', 'iab.com'],
  'bidder:hypelab': ['hypelab.com', 'iab.com'],
  'bidder:hyperbrainz': ['hyperbrainz.com'],
  'bidder:id': ['360yield-basic.com', '360yield.com', 'adnxs.com', 'iab.com', 'improvedigital.com'],
  'bidder:idx': ['dxmdp.com'],
  'bidder:iionads': ['iab.com', 'iion.io', 'orangeclickmedia.com'],
  'bidder:illumin': ['admanmedia.com', 'cootlogix.com', 'illumin.com', 'npm.im'],
  'bidder:imds': ['technoratimedia.com'],
  'bidder:imp': ['impactify.io', 'impactify.media'],
  'bidder:impactify': ['impactify.io', 'impactify.media'],
  'bidder:improvedigital': ['360yield-basic.com', '360yield.com', 'adnxs.com', 'iab.com', 'improvedigital.com'],
  'bidder:incrementx': ['incrementxserv.com'],
  'bidder:incrx': ['incrementxserv.com'],
  'bidder:indicue': ['adtelligent.com', 'npm.im'],
  'bidder:infinety': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:inmobi': ['iab.com', 'inmobi.com'],
  'bidder:innity': ['innity.com', 'innity.net'],
  'bidder:insticator': ['ingage.tech', 'insticator.com'],
  'bidder:insurads': ['adnxs.com', 'iab.com', 'insurads.com', 'nexx360.io'],
  'bidder:integr8': ['integr8.digital'],
  'bidder:interactiveOffers': ['ioadx.com'],
  'bidder:intlscoop': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:invamia': ['invamia.com'],
  'bidder:invibes': ['invibes.com', 'r66net.com'],
  'bidder:iprom': ['iab.com', 'iprom.net'],
  'bidder:iqx': ['iqzonertb.live'],
  'bidder:iqzone': ['iqzone.com'],
  'bidder:ivs': ['iab.com', 'ivstracker.net'],
  'bidder:ix': ['casalemedia.com', 'indexexchange.com', 'indexww.com'],
  'bidder:jambojar': ['attekmi.co', 'shb-sync.com'],
  'bidder:jdpmedia': ['attekmi.co', 'shb-sync.com'],
  'bidder:jixie': ['jixie.io', 'jixie.media'],
  'bidder:jjtech': ['iab.com', 'jambojar-tech.com'],
  'bidder:justpremium': ['justpremium.com'],
  'bidder:jwplayer': ['adnxs.com', 'jwplayer.com'],
  'bidder:kargo': ['kargo.com'],
  'bidder:kimberlite': ['iab.com', 'kimberlite.io'],
  'bidder:kivi': ['kiviads.live'],
  'bidder:kiviads': ['kiviads.com'],
  'bidder:kobler': ['essrtb.com'],
  'bidder:krushmedia': ['krushmedia.com'],
  'bidder:kuantyx': ['adserver.online', 'aso1.net', 'bidgx.com', 'iab.com', 'kuantyx.com'],
  'bidder:kubient': ['kbntx.ch', 'kubient.net'],
  'bidder:kueezrtb': ['cootlogix.com', 'kueez.com', 'kueezrtb.com', 'npm.im'],
  'bidder:lane4': ['lane4.io'],
  'bidder:lasso': ['adnxs.com', 'lhmos.com'],
  'bidder:league-m': ['adnxs.com', 'first-id.fr', 'glomex.com', 'iab.com', 'nexx360.io', 'plug.it', 'pubx.ai', 'yieldbird.com'],
  'bidder:leagueM': ['league-m.media'],
  'bidder:lemmadigital': ['lemmadigital.com', 'lemmamedia.com'],
  'bidder:lifestreet': ['lfstmedia.com'],
  'bidder:limelightDigital': ['iab.com', 'iion.io', 'orangeclickmedia.com'],
  'bidder:livewrapped': ['lwadm.com'],
  'bidder:lm_kiviads': ['kiviads.live'],
  'bidder:lockerdome': ['lockerdome.com'],
  'bidder:logan': ['logan.ai'],
  'bidder:logicad': ['ladsp.com'],
  'bidder:logly': ['logly.co.jp'],
  'bidder:loopme': ['iab.com', 'loopme.ai', 'loopmertb.com'],
  'bidder:loyal': ['loyal.app'],
  'bidder:lsm': ['lfstmedia.com'],
  'bidder:lucead': ['iab.com'],
  'bidder:lunamediahb': ['lunamedia.bid', 'lunamedia.io'],
  'bidder:lunamediax': ['xe.works'],
  'bidder:luponmedia': ['iab.com', 'luponmedia.com'],
  'bidder:m152': ['152media-ssp.com', '152media.info'],
  'bidder:mabidder': ['ecdrsvc.com', 'iab.com'],
  'bidder:madsense': ['iab.com', 'madsense.io'],
  'bidder:madvertise': ['bluestack.app', 'mng-ads.com'],
  'bidder:magicbid': ['rtb-magicbid.ai'],
  'bidder:magnite': ['iab.com', 'rubiconproject.com'],
  'bidder:malltv': ['mall.tv'],
  'bidder:mantis': ['mantisadnetwork.com'],
  'bidder:markapp': ['attekmi.co', 'shb-sync.com'],
  'bidder:mars': ['go2speed.media', 'mars.media'],
  'bidder:marsmedia': ['go2speed.media', 'mars.media'],
  'bidder:mathildeads': ['mathilde-ads.com'],
  'bidder:matomy': ['adnxs-simple.com', 'adnxs.com', 'adzymic.com', 'appnexus.com', 'b-cdn.net', 'linkedin.com', 'npm.im', 'projectagora.net'],
  'bidder:matterfull': ['bematterfull.com'],
  'bidder:mediabrama': ['mediabrama.com'],
  'bidder:mediaConsortium': ['hubvisor.io'],
  'bidder:mediaeyes': ['upremium.asia'],
  'bidder:mediaforce': ['comparisons.org', 'mfadsrvr.com'],
  'bidder:mediafuse': ['adnxs-simple.com', 'adnxs.com', 'iab.com', 'npm.im'],
  'bidder:mediago': ['mediago.io', 'mediagotechnology.com'],
  'bidder:mediakeys': ['iab.com', 'mediakeys.io'],
  'bidder:medianet': ['media.net', 'trustedstack.com'],
  'bidder:mediaopti': ['adxcg.net', 'iab.com'],
  'bidder:mediasniper': ['bumlam.com'],
  'bidder:mediasquare': ['adnxs.com', 'mediasquare.fr'],
  'bidder:mgid': ['iab.com', 'mgid.com'],
  'bidder:mgidX': ['mgid.com'],
  'bidder:mgtechnology': ['mediago.io', 'mediagotechnology.com'],
  'bidder:michao': ['iab.com', 'michao-ssp.com'],
  'bidder:microad': ['microad.jp'],
  'bidder:mile': ['atmtd.com'],
  'bidder:minutemedia': ['minutemedia-prebid.com', 'mmctsvc.com', 'yellowblue.io'],
  'bidder:missena': ['missena.io'],
  'bidder:mobfoxpb': ['mobfox.com'],
  'bidder:mobilefuse': ['iab.com', 'mobilefuse.com'],
  'bidder:mobkoi': ['iab.com', 'mobkoi.com'],
  'bidder:monetixads': ['admatic.com.tr', 'admatic.de', 'adnxs.com', 'adtarget.com.tr'],
  'bidder:motionspots': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:movingup': ['adnxs.com', 'iab.com', 'nexx360.io'],
  'bidder:msft': ['adnxs-simple.com', 'adnxs.com', 'linkedin.com'],
  'bidder:msftstaila': ['adnxs-simple.com', 'adnxs.com', 'linkedin.com'],
  'bidder:msna': ['missena.io'],
  'bidder:msq': ['adnxs.com', 'mediasquare.fr'],
  'bidder:mtc': ['adnxs.com', 'iab.com', 'nexx360.io'],
  'bidder:my6sense': ['mynativeplatform.com'],
  'bidder:mycodemedia': ['mycodemedia.com'],
  'bidder:myfeature': ['featuretv.bid', 'ferio.bid'],
  'bidder:mytarget': ['mail.ru'],
  'bidder:nat': ['iab.com', 'nativery.com', 'npm.im'],
  'bidder:nativery': ['iab.com', 'nativery.com', 'npm.im'],
  'bidder:nativo': ['iab.com', 'nativo.com', 'postrelease.com'],
  'bidder:netaddiction': ['admatic.com.tr', 'admatic.de', 'adnxs.com', 'adtarget.com.tr'],
  'bidder:netads': ['adnxs.com', 'first-id.fr', 'glomex.com', 'iab.com', 'nexx360.io', 'plug.it', 'pubx.ai', 'yieldbird.com'],
  'bidder:newdream': ['adnxs-simple.com', 'adnxs.com', 'adzymic.com', 'appnexus.com', 'b-cdn.net', 'linkedin.com', 'npm.im', 'projectagora.net'],
  'bidder:newspassid': ['aditude.com', 'amspbs.com', 'iab.com'],
  'bidder:nextMillennium': ['adnxs.com', 'nextmillennium.io', 'nextmillmedia.com', 'prebrid.tv', 'target-video.com'],
  'bidder:nextroll': ['adroll.com'],
  'bidder:nexverse': ['nexverse.ai'],
  'bidder:nexx360': ['adnxs.com', 'first-id.fr', 'glomex.com', 'iab.com', 'nexx360.io', 'plug.it', 'pubx.ai', 'yieldbird.com'],
  'bidder:nobid': ['nobid.com', 'servenobid.com'],
  'bidder:ntv': ['iab.com', 'nativo.com', 'postrelease.com'],
  'bidder:ntvagents': ['nativeagents.ai'],
  'bidder:nuba': ['nuba.io'],
  'bidder:nuclion': ['iab.com', 'iion.io', 'orangeclickmedia.com'],
  'bidder:ocm': ['iab.com', 'orangeclickmedia.com'],
  'bidder:oftmedia': ['adnxs-simple.com', 'adnxs.com', 'linkedin.com'],
  'bidder:oftmediahb': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:ogury': ['iab.com', 'ogury.co', 'presage.io'],
  'bidder:omnidex': ['cootlogix.com', 'npm.im', 'omni-dex.io'],
  'bidder:oms': ['marphezis.com'],
  'bidder:onetag': ['onetag-cdn.com', 'onetag-sys.com'],
  'bidder:onomagic': ['onomagic.com'],
  'bidder:opamarketplace': ['cootlogix.com', 'npm.im', 'opamarketplace.com'],
  'bidder:open8': ['open8.com'],
  'bidder:openweb': ['openwebmp.com', 'yellowblue.io'],
  'bidder:openwebvideo': ['aniview.com', 'iab.com'],
  'bidder:openwebxchange': ['yellowblue.io'],
  'bidder:openx': ['iab.com', 'openx.com', 'openx.net'],
  'bidder:opera': ['adnxs.com', 'iab.com', 'opera.com'],
  'bidder:operaads': ['adnxs.com', 'iab.com', 'opera.com'],
  'bidder:oppamedia': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:oprx': ['iab.com', 'optimizerx.com'],
  'bidder:opsco': ['iab.com', 'ops.co'],
  'bidder:optidigital': ['opti-digital.com', 'optidigital.com'],
  'bidder:optout': ['optinadserving.com', 'optoutadserving.com', 'optoutadvertising.com'],
  'bidder:oraki': ['oraki.io'],
  'bidder:orangeclickmedia': ['iab.com', 'iion.io', 'orangeclickmedia.com'],
  'bidder:orbidder': ['otto.de'],
  'bidder:otm': ['otm-r.com'],
  'bidder:ottadvisors': ['aniview.com', 'iab.com'],
  'bidder:outbrain': ['adnxs.com', 'outbrain.com'],
  'bidder:oveeo': ['iab.com', 'iion.io', 'orangeclickmedia.com'],
  'bidder:ownadx': ['prebid-ownadx.com'],
  'bidder:ozone': ['the-ozone-project.com'],
  'bidder:padsquad': ['padsquad.com'],
  'bidder:pagescience': ['adnxs-simple.com', 'adnxs.com', 'adzymic.com', 'appnexus.com', 'b-cdn.net', 'linkedin.com', 'npm.im', 'projectagora.net'],
  'bidder:pangle': ['i18n-pglstatp.com', 'iab.com', 'pangleglobal.com'],
  'bidder:panxo': ['panxo-sys.com', 'panxo.ai'],
  'bidder:performax': ['iab.com', 'performax.cz'],
  'bidder:performist': ['iab.com', 'iion.io', 'orangeclickmedia.com'],
  'bidder:pgamdirect': ['iab.com', 'pgammedia.com'],
  'bidder:pgammedia': ['aniview.com', 'iab.com'],
  'bidder:pgamrtb': ['iab.com', 'iion.io', 'orangeclickmedia.com'],
  'bidder:pgamssp': ['pgammedia.com'],
  'bidder:pigeoon': ['pigeoon.com'],
  'bidder:pilotx': ['pilotx.tv'],
  'bidder:pinelake': ['pinelake.media'],
  'bidder:pinkLion': ['pinklion.io'],
  'bidder:pixad': ['admatic.com.tr', 'admatic.de', 'adnxs.com', 'adtarget.com.tr'],
  'bidder:pixelpluses': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:pixfuture': ['pixfuture.com'],
  'bidder:playdigo': ['playdigo.com'],
  'bidder:playgroundxyz': ['adnxs.com', 'gumgum.com', 'playground.xyz'],
  'bidder:playstream': ['iab.com'],
  'bidder:playwire': ['adnxs.com', 'bidswitch.net', 'themediagrid.com'],
  'bidder:pll': ['iab.com', 'iion.io', 'orangeclickmedia.com'],
  'bidder:plr': ['publir.com', 'yellowblue.io'],
  'bidder:preciso': ['2trk.info', 'preciso.net'],
  'bidder:prisma': ['nexx360.io'],
  'bidder:prismadirect': ['nexx360.io'],
  'bidder:prismassp': ['adnxs.com', 'first-id.fr', 'glomex.com', 'iab.com', 'nexx360.io', 'plug.it', 'pubx.ai', 'yieldbird.com'],
  'bidder:prjads': ['adnxs.com', 'first-id.fr', 'glomex.com', 'iab.com', 'nexx360.io', 'plug.it', 'pubx.ai', 'yieldbird.com'],
  'bidder:programmaticX': ['cootlogix.com', 'npm.im', 'programmaticx.ai', 'progrtb.com'],
  'bidder:projectagora': ['adnxs-simple.com', 'adnxs.com', 'adzymic.com', 'appnexus.com', 'b-cdn.net', 'linkedin.com', 'npm.im', 'projectagora.net'],
  'bidder:proxistore': ['cookieless-proxistore.com', 'iab.com', 'proxistore.com'],
  'bidder:pstudio': ['adsrvr.org', 'tadex.id', 'telkomsel.com'],
  'bidder:pubcircle': ['pubcircle.ai'],
  'bidder:pubgenius': ['adpearl.io'],
  'bidder:publicgood': ['pgs.io', 'publicgood.com'],
  'bidder:publir': ['publir.com', 'yellowblue.io'],
  'bidder:pubmatic': ['bbvms.com', 'iab.com', 'pubmatic.com'],
  'bidder:pubrise': ['pubrise.ai'],
  'bidder:pubstack': ['iab.com', 'pbstck.com'],
  'bidder:pubstack_server': ['iab.com', 'pbstck.com'],
  'bidder:pubtech': ['adnxs.com', 'first-id.fr', 'glomex.com', 'iab.com', 'nexx360.io', 'plug.it', 'pubx.ai', 'yieldbird.com'],
  'bidder:pubwise': ['pubwise.io'],
  'bidder:pubx': ['primecaster.net'],
  'bidder:pubxai': ['adnxs.com', 'first-id.fr', 'glomex.com', 'iab.com', 'nexx360.io', 'plug.it', 'pubx.ai', 'yieldbird.com'],
  'bidder:pulseLite': ['contextweb.com', 'iab.com'],
  'bidder:pulsepoint': ['contextweb.com', 'iab.com'],
  'bidder:pulsepointLite': ['contextweb.com', 'iab.com'],
  'bidder:pwbid': ['pubwise.io'],
  'bidder:px': ['iab.com', 'performax.cz'],
  'bidder:pxyz': ['adnxs.com', 'gumgum.com', 'playground.xyz'],
  'bidder:qohere': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:qortex': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:qt': ['qt.io'],
  'bidder:quantumdex': ['quantumdex.io'],
  'bidder:qwarry': ['qwarry.co'],
  'bidder:r2b2': ['iab.com', 'r2b2.io'],
  'bidder:ra': ['richaudience.com'],
  'bidder:radiantfusion': ['attekmi.co', 'shb-sync.com'],
  'bidder:readpeak': ['readpeak.com'],
  'bidder:realry': ['iab.com', 'realry.com'],
  'bidder:rediads': ['iab.com', 'rediads.com'],
  'bidder:redtram': ['redtram.com'],
  'bidder:reklamup': ['reklamup.com'],
  'bidder:relay': ['iab.com', 'relay.bid'],
  'bidder:relevantdigital': ['iab.com', 'relevant-digital.com'],
  'bidder:relevatehealth': ['relevate.health'],
  'bidder:reload': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:resetdigital': ['resetdigital.co', 'resetsrv.com'],
  'bidder:responsiveads': ['iab.com', 'responsiveads.com'],
  'bidder:revantage': ['revantage.io'],
  'bidder:revbid': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:revbidortb': ['revantage.io'],
  'bidder:revcontent': ['revcontent.com'],
  'bidder:revealon': ['revealonmedia.live'],
  'bidder:revenuemaker': ['adnxs.com', 'first-id.fr', 'glomex.com', 'iab.com', 'nexx360.io', 'plug.it', 'pubx.ai', 'yieldbird.com'],
  'bidder:revnew': ['adnxs.com', 'iab.com', 'mediafuse.com', 'nexx360.io'],
  'bidder:rhythmone': ['1rx.io', 'unrulymedia.com'],
  'bidder:richaudience': ['richaudience.com'],
  'bidder:ringieraxelspringer': ['ocdn.eu', 'onet.pl'],
  'bidder:rise': ['yellowblue.io'],
  'bidder:risemediatech': ['adsmartx.com', 'iab.com', 'risemediatech.com'],
  'bidder:risexchange': ['yellowblue.io'],
  'bidder:rixengine': ['algorix.co', 'iab.com'],
  'bidder:robusta': ['iab.com'],
  'bidder:robustApps': ['rbstsystems.live'],
  'bidder:rocketlab': ['rocketlab.ai'],
  'bidder:rtbdemand': ['iab.com', 'iion.io', 'orangeclickmedia.com'],
  'bidder:rtbdemand_com': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:rtbhouse': ['rtbhouse.com'],
  'bidder:rtbsape': ['acint.net', 'sape.ru'],
  'bidder:rtbstack': ['admixer.com', 'admixer.net', 'futureads.io', 'go2net.com.ua', 'smn.rs'],
  'bidder:rubicon': ['iab.com', 'rubiconproject.com'],
  'bidder:rumble': ['rmbl.ws'],
  'bidder:saambaa': ['advangelists.com', 'beachfrontmedia.com'],
  'bidder:sape': ['acint.net', 'sape.ru'],
  'bidder:scalibur': ['overwolf.com'],
  'bidder:scattered': ['iab.com'],
  'bidder:scm': ['freeskreen.com'],
  'bidder:scoremedia': ['adnxs.com', 'first-id.fr', 'glomex.com', 'iab.com', 'nexx360.io', 'plug.it', 'pubx.ai', 'yieldbird.com'],
  'bidder:screencore': ['screencore.io'],
  'bidder:seedingAlliance': ['iab.com', 'nativendo.de'],
  'bidder:seedtag': ['seedtag.com', 'web.dev'],
  'bidder:selectmedia': ['selectmedia.asia', 'zxyvrtd.com'],
  'bidder:selectmediavideo': ['aniview.com', 'iab.com'],
  'bidder:setupad': ['iab.com', 'setupad.io', 'stpd.cloud'],
  'bidder:sevio': ['adx.ws', 'iab.com', 'sevio.com'],
  'bidder:sharethrough': ['iab.com', 'sharethrough.com', 'smartadserver.com'],
  'bidder:shinez': ['sweetgum.io', 'yellowblue.io'],
  'bidder:shinezRtb': ['cootlogix.com', 'npm.im', 'sweetgum.io'],
  'bidder:showheroes': ['iab.com', 'showheroes.com', 'viralize.tv'],
  'bidder:showheroes-bs': ['iab.com', 'showheroes.com', 'viralize.tv'],
  'bidder:showheroesBs': ['iab.com', 'showheroes.com', 'viralize.tv'],
  'bidder:silvermob': ['iab.com', 'silvermob.com'],
  'bidder:silverpush': ['chocolateplatform.co', 'digitaloceanspaces.com', 'iab.com'],
  'bidder:slimcut': ['freeskreen.com'],
  'bidder:smaato': ['iab.com', 'smaato.com', 'smaato.net'],
  'bidder:smart': ['smartadserver.com'],
  'bidder:smartadserver': ['smartadserver.com'],
  'bidder:smarthub': ['attekmi.co', 'shb-sync.com'],
  'bidder:smartico': ['trmads.eu'],
  'bidder:smartx': ['smartclip.net'],
  'bidder:smartyads': ['ck-ie.com', 'smartyads.com'],
  'bidder:smartyexchange': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:smartytech': ['npm.im'],
  'bidder:smb': ['smartbid.ai'],
  'bidder:smile': ['smilewanted.com'],
  'bidder:smilewanted': ['smilewanted.com'],
  'bidder:smn': ['admixer.com', 'admixer.net', 'futureads.io', 'go2net.com.ua', 'smn.rs'],
  'bidder:smoot': ['smoot.ai', 'smxconv.com'],
  'bidder:smootai': ['iab.com', 'iion.io', 'orangeclickmedia.com'],
  'bidder:snigel': ['snigelweb.com'],
  'bidder:sonarads': ['bridgeupp.com', 'iab.com', 'sonar-ads.com'],
  'bidder:sonobi': ['sonobi.com'],
  'bidder:sovrn': ['lijit.com', 'sovrn.com'],
  'bidder:sparteo': ['bricks-co.com', 'iab.com', 'sparteo.com'],
  'bidder:spinx': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:spm': ['adnxs.com', 'first-id.fr', 'glomex.com', 'iab.com', 'nexx360.io', 'plug.it', 'pubx.ai', 'yieldbird.com'],
  'bidder:ssmas': ['iab.com', 'semseoymas.com', 'ssmas.com'],
  'bidder:ssp_geniee': ['genieesspv.jp', 'gssprt.jp'],
  'bidder:sspBC': ['wp.pl'],
  'bidder:st': ['seedtag.com', 'web.dev'],
  'bidder:stackadapt': ['iab.com', 'stackadapt.com'],
  'bidder:stackup': ['attekmi.co', 'shb-sync.com'],
  'bidder:stailamedia': ['adnxs-simple.com', 'adnxs.com', 'adzymic.com', 'appnexus.com', 'b-cdn.net', 'linkedin.com', 'npm.im', 'projectagora.net'],
  'bidder:startio': ['iab.com', 'startappnetwork.com', 'startappservice.com'],
  'bidder:stellorMediaRtb': ['iab.com', 'iion.io', 'orangeclickmedia.com'],
  'bidder:stn': ['stngo.com', 'yellowblue.io'],
  'bidder:streamvision': ['iab.com', 'iion.io', 'orangeclickmedia.com'],
  'bidder:stroeerCore': ['adscale.de', 'stroeer.de'],
  'bidder:stv': ['adtech.app', 'smartstream.tv'],
  'bidder:sublime': ['ayads.co'],
  'bidder:suim': ['suimad.com'],
  'bidder:sw': ['smilewanted.com'],
  'bidder:synacormedia': ['technoratimedia.com'],
  'bidder:synapsehx': ['compasonline.com', 'iab.com'],
  'bidder:taboola': ['iab.com', 'taboola.com'],
  'bidder:tadvertising': ['adsrvr.org', 'emetriq.de', 'iab.com', 'xplosion.de'],
  'bidder:tagoras': ['cootlogix.com', 'npm.im', 'tagoras.io'],
  'bidder:tapnative': ['tapnative.com'],
  'bidder:tappx': ['tappx.com'],
  'bidder:targetVideo': ['adnxs.com', 'prebrid.tv', 'target-video.com'],
  'bidder:teads': ['teads.tv'],
  'bidder:teal': ['bids.ws', 'iab.com'],
  'bidder:temedya': ['vidyome.com'],
  'bidder:teqBlazeSalesAgent': ['teqblaze.io'],
  'bidder:tgm': ['iab.com', 'iion.io', 'orangeclickmedia.com'],
  'bidder:theads': ['admixer.com', 'admixer.net', 'futureads.io', 'go2net.com.ua', 'smn.rs'],
  'bidder:theadx': ['theadx.com'],
  'bidder:theAdx': ['theadx.com'],
  'bidder:themoneytizer': ['biddertmz.com'],
  'bidder:thetradedesk': ['adsrvr.org'],
  'bidder:tne_catalyst': ['thenexusengine.com', 'thenexusengine.io'],
  'bidder:topon': ['anyrtb.com', 'toponad.net'],
  'bidder:tpmn': ['adnxs.com', 'appier.net', 'aralego.com', 'bidswitch.net', 'iab.com', 'mmnneo.com', 'tpmn.io'],
  'bidder:tqblz_demo': ['teqblaze.com'],
  'bidder:trafficgate': ['iab.com'],
  'bidder:tredio': ['attekmi.co', 'shb-sync.com'],
  'bidder:trek': ['aotter.net'],
  'bidder:trion': ['in-appadvertising.com'],
  'bidder:triplelift': ['3lift.com'],
  'bidder:truereach': ['momagic.com'],
  'bidder:trustedstack': ['media.net', 'trustedstack.com'],
  'bidder:trustx': ['adnxs.com', 'iab.com', 'trustx.org'],
  'bidder:ttd': ['adsrvr.org'],
  'bidder:turktelekom': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:twistdigital': ['cootlogix.com', 'npm.im', 'twist.win', 'twistdigital.net'],
  'bidder:ucfunnel': ['aralego.com', 'aralego.net'],
  'bidder:uncn': ['uncn.jp'],
  'bidder:underdogmedia': ['udmserve.net', 'underdog.media'],
  'bidder:undertone': ['undertone.com'],
  'bidder:unibots': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:unicorn': ['uncn.jp'],
  'bidder:uniquest': ['ust-ad.com'],
  'bidder:uniquest_widget': ['ust-ad.com'],
  'bidder:unruly': ['unrulymedia.com'],
  'bidder:uol': ['adnxs-simple.com', 'adnxs.com', 'adzymic.com', 'appnexus.com', 'b-cdn.net', 'linkedin.com', 'npm.im', 'projectagora.net'],
  'bidder:urekamedia': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:vaayaMedia': ['iab.com', 'iion.io', 'orangeclickmedia.com'],
  'bidder:valuad': ['appspot.com', 'iab.com', 'valuad.cloud', 'valuad.io'],
  'bidder:valueimpression': ['quantumdex.io'],
  'bidder:velonium': ['iab.com', 'iion.io', 'orangeclickmedia.com'],
  'bidder:ventes': ['ventesavenues.in'],
  'bidder:verben': ['verben.com'],
  'bidder:viant': ['adelphic.net', 'iab.com'],
  'bidder:viantortb': ['adelphic.net', 'iab.com'],
  'bidder:vibrantmedia': ['intellitxt.com'],
  'bidder:vidazoo': ['cootlogix.com', 'npm.im', 'vidazoo.com'],
  'bidder:vidcrunch': ['aniview.com', 'iab.com'],
  'bidder:videobyte': ['videobyte.com'],
  'bidder:videoheroes': ['contextualadv.com'],
  'bidder:videonow': ['videonow.ru'],
  'bidder:videoreach': ['videoreach.com'],
  'bidder:vidoomy': ['adform.net', 'bidswitch.net', 'openx.net', 'pubmatic.com', 'rubiconproject.com', 'sitescout.com', 'vidoomy.com'],
  'bidder:viously': ['bricks-co.com', 'viously.com'],
  'bidder:viqeo': ['viqeo.tv', 'vqserve.com'],
  'bidder:visiblemeasures': ['visiblemeasures.com'],
  'bidder:vistars': ['iab.com'],
  'bidder:visx': ['visx.net', 'yoc.com'],
  'bidder:vlyby': ['vlyby.com'],
  'bidder:voisetech': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:vox': ['adnxs.com', 'hybrid.ai'],
  'bidder:vrtcal': ['vrtcal.com'],
  'bidder:vuukle': ['iab.com', 'vuukle.com'],
  'bidder:waardex': ['exmpale.com', 'justbidit2.xyz'],
  'bidder:waardex_ak': ['adkernel.com', 'appmonsta.ai', 'converge-digital.com', 'memob.com', 'spinx.biz'],
  'bidder:welect': ['welect.de'],
  'bidder:wi': ['reckoner-api.com'],
  'bidder:widespace': ['widespace.com'],
  'bidder:winr': ['adnxs-simple.com', 'adnxs.com', 'winr.com.au'],
  'bidder:wipes': ['reckoner-api.com'],
  'bidder:wlt': ['welect.de'],
  'bidder:wmg': ['adwmg.com'],
  'bidder:wnr': ['adnxs-simple.com', 'adnxs.com', 'winr.com.au'],
  'bidder:xe': ['xe.works'],
  'bidder:xeworks': ['xe.works'],
  'bidder:y1': ['cmertv.com', 'impact-ad.jp'],
  'bidder:yahooAds': ['yahoo.com', 'yimg.com'],
  'bidder:yahooAdvertising': ['yahoo.com', 'yimg.com'],
  'bidder:yahoossp': ['yahoo.com', 'yimg.com'],
  'bidder:yaleo': ['audienzz.com', 'iab.com', 'yaleo.com'],
  'bidder:ybidder': ['adnxs.com', 'first-id.fr', 'glomex.com', 'iab.com', 'nexx360.io', 'plug.it', 'pubx.ai', 'yieldbird.com'],
  'bidder:yieldlab': ['adition.com', 'yieldlab.net'],
  'bidder:yieldlift': ['yieldlift.com'],
  'bidder:yieldlove': ['yieldlove-ad-serving.net', 'yieldlove.com'],
  'bidder:yieldmo': ['yieldmo.com'],
  'bidder:yieldone': ['cmertv.com', 'impact-ad.jp'],
  'bidder:yl': ['yieldlift.com'],
  'bidder:yobee': ['admatic.com.tr', 'admatic.de', 'adnxs.com', 'adtarget.com.tr'],
  'bidder:zeta': ['rfihub.com', 'zetaglobal.com'],
  'bidder:zeta_global': ['rfihub.com', 'zetaglobal.com'],
  'bidder:zeta_global_ssp': ['disqus.com', 'zetaglobal.com'],
  'bidder:zmaticoo': ['zmaticoo.com'],
  'rtd:51Degrees': ['51degrees.com'],
  'rtd:a1Media': ['contentsfeed.com'],
  'rtd:adagio': ['4dex.io', 'adagio.io'],
  'rtd:adloox': ['adloox.com', 'adlooxtracking.com'],
  'rtd:adnuntius': ['adnuntius.com'],
  'rtd:airgrid': ['edkt.io', 'wearemiq.com'],
  'rtd:anonymised': ['anonymised.io'],
  'rtd:azerionedge': ['hyth.io', 'improvedigital.com'],
  'rtd:brandmetrics': ['brandmetrics.com'],
  'rtd:confiant': ['confiant-integrations.net'],
  'rtd:datamage': ['opsmage-api.io'],
  'rtd:dgkeyword': ['opecloud.com'],
  'rtd:dynamicAdBoost': ['adxbid.info'],
  'rtd:encypher': ['encypher.com'],
  'rtd:experian_rtid': ['tapad.com'],
  'rtd:geoedge': ['geoedge.be'],
  'rtd:goldfishAdsRtd': ['goldfishads.com'],
  'rtd:greenbidsRtdProvider': ['greenbids.ai'],
  'rtd:growthCodeRtd': ['gcprivacy.com'],
  'rtd:hadron': ['ad.gt', 'hadronid.net'],
  'rtd:humansecurity': ['script.ac'],
  'rtd:ias': ['adsafeprotected.com'],
  'rtd:im': ['im-apps.net'],
  'rtd:insuradsRtd': ['insurads.com'],
  'rtd:liveintent': ['liadm.com'],
  'rtd:mediafilter': ['themediatrust.com', 'webcontentassessor.com'],
  'rtd:medianet': ['media.net'],
  'rtd:mgid': ['mgid.com'],
  'rtd:mobianBrandSafety': ['outcomes.net'],
  'rtd:NeuwoRTDModule': ['neuwo.ai'],
  'rtd:nodalsAi': ['nodals.ai', 'nodals.io'],
  'rtd:oftmedia': ['152media.info'],
  'rtd:optimeraRTD': ['oapi26b.com'],
  'rtd:overtone': ['overtone.ai'],
  'rtd:panxo': ['idsequoia.ai'],
  'rtd:permutive': ['permutive.app'],
  'rtd:pubmatic': ['pubmatic.com'],
  'rtd:pubxai': ['pbxai.com'],
  'rtd:qortex': ['qortex.ai'],
  'rtd:raveltech': ['rvlproxy.net'],
  'rtd:reconciliation': ['fiduciadlt.com'],
  'rtd:RelevadRTDModule': ['relestar.com'],
  'rtd:scope3': ['scope3.com'],
  'rtd:semantiq': ['adnz.co', 'audienzz.com'],
  'rtd:SirdataRTDModule': ['sirdata.eu', 'sirdata.io'],
  'rtd:stackupRtd': ['stackup-ai.com'],
  'rtd:weborama': ['weborama.fr'],
  'rtd:wurfl': ['wurflcloud.com'],
  'userId:33acrossId': ['33across.com'],
  'userId:abtshieldId': ['abtshield.com'],
  'userId:acxiomRealId': ['gcprivacy.id'],
  'userId:admixerId': ['admixer.com', 'admixer.net'],
  'userId:adplusId': ['ad-plus.com.tr'],
  'userId:adriverId': ['adriver.ru'],
  'userId:adtelligent': ['adtelligent.com'],
  'userId:amxId': ['a-mo.net', 'a-mx.com'],
  'userId:ceeId': ['ceeid.eu', 'wp.pl'],
  'userId:connectId': ['yahoo.com'],
  'userId:criteo': ['criteo.com'],
  'userId:czechAdId': ['cpex.cz'],
  'userId:dacId': ['impact-ad.jp'],
  'userId:euid': ['euid.eu'],
  'userId:fabrickId': ['agkn.com'],
  'userId:gemiusId': ['gemius.com'],
  'userId:hadronId': ['ad.gt'],
  'userId:id5Id': ['id5-sync.com'],
  'userId:identityLink': ['rlcdn.com'],
  'userId:intentIqId': ['geeksforgeeks.org', 'intentiq.com'],
  'userId:jixieId': ['jixie.io'],
  'userId:justId': ['audience-solutions.com'],
  'userId:kpuid': ['knsso.com'],
  'userId:liveIntentId': ['liadm.com'],
  'userId:locId': ['apache.org'],
  'userId:locid': ['apache.org'],
  'userId:lockrAIMId': ['loc.kr'],
  'userId:lotamePanoramaId': ['crwdcntrl.net'],
  'userId:merkleId': ['rkdms.com'],
  'userId:mobkoiId': ['mobkoi.com', 'smartadserver.com'],
  'userId:mwOpenLinkId': ['mediawallahscript.com'],
  'userId:mygaruId': ['mygaru.com'],
  'userId:naveggId': ['navegg.com'],
  'userId:novatiq': ['novatiq.com', 'spadsync.com'],
  'userId:operaId': ['opera.com'],
  'userId:permutiveIdentityManagerId': ['permutive.app'],
  'userId:publinkId': ['dotomi.com'],
  'userId:pubmaticId': ['pubmatic.com'],
  'userId:qid': ['adquery.io'],
  'userId:startioId': ['startappnetwork.com', 'startappservice.com'],
  'userId:taboolaId': ['taboola.com'],
  'userId:tapadId': ['tapad.com'],
  'userId:teadsId': ['teads.tv'],
  'userId:tncId': ['tncid.app'],
  'userId:uid2': ['uidapi.com'],
  'userId:unifiedId': ['adsrvr.org'],
  'userId:zeotapIdPlus': ['rqtrk.eu'],
};
