/**
 * Endpoint domains each prebid user id / RTD module calls, used to attribute network requests to the
 * provider that made them.
 *
 * GENERATED - do not edit by hand.
 * Run `node utils/prebidMetadata/extractProviderHosts.mjs` after bumping prebid.js.
 *
 * Keys are `<componentType>:<componentName>`, matching the names used in
 * `realTimeData.dataProviders[].name` and `userSync.userIds[].name`.
 *
 * Documentation links and shared infrastructure (amazonaws, gstatic, doubleclick...) are excluded: a
 * missing attribution is better than a wrong one. Modules whose endpoint comes from publisher config
 * are absent on purpose - those hosts are read from the live config instead.
 */
export const PROVIDER_HOSTS: { [typeAndName: string]: string[] } = {
  'rtd:51Degrees': ['51degrees.com'],
  'rtd:a1Media': ['contentsfeed.com'],
  'rtd:adagio': ['4dex.io', 'adagio.io'],
  'rtd:adloox': ['adloox.com', 'adlooxtracking.com'],
  'rtd:adnuntius': ['adnuntius.com'],
  'rtd:airgrid': ['edkt.io', 'wearemiq.com'],
  'rtd:anonymised': ['anonymised.io'],
  'rtd:azerionedge': ['hyth.io', 'improvedigital.com'],
  'rtd:brandmetrics': ['brandmetrics.com'],
  'rtd:confiant': ['confiant-integrations.net'],
  'rtd:datamage': ['opsmage-api.io'],
  'rtd:dgkeyword': ['opecloud.com'],
  'rtd:dynamicAdBoost': ['adxbid.info'],
  'rtd:encypher': ['encypher.com'],
  'rtd:experian_rtid': ['tapad.com'],
  'rtd:geoedge': ['geoedge.be'],
  'rtd:goldfishAdsRtd': ['goldfishads.com'],
  'rtd:greenbidsRtdProvider': ['greenbids.ai'],
  'rtd:growthCodeRtd': ['gcprivacy.com'],
  'rtd:hadron': ['ad.gt', 'hadronid.net'],
  'rtd:humansecurity': ['script.ac'],
  'rtd:ias': ['adsafeprotected.com'],
  'rtd:im': ['im-apps.net'],
  'rtd:insuradsRtd': ['insurads.com'],
  'rtd:liveintent': ['liadm.com'],
  'rtd:mediafilter': ['themediatrust.com', 'webcontentassessor.com'],
  'rtd:medianet': ['media.net'],
  'rtd:mgid': ['mgid.com'],
  'rtd:mobianBrandSafety': ['outcomes.net'],
  'rtd:NeuwoRTDModule': ['neuwo.ai'],
  'rtd:nodalsAi': ['nodals.ai', 'nodals.io'],
  'rtd:oftmedia': ['152media.info'],
  'rtd:optimeraRTD': ['oapi26b.com'],
  'rtd:overtone': ['overtone.ai'],
  'rtd:panxo': ['idsequoia.ai'],
  'rtd:permutive': ['permutive.app'],
  'rtd:pubmatic': ['pubmatic.com'],
  'rtd:pubxai': ['pbxai.com'],
  'rtd:qortex': ['qortex.ai'],
  'rtd:raveltech': ['rvlproxy.net'],
  'rtd:reconciliation': ['fiduciadlt.com'],
  'rtd:RelevadRTDModule': ['relestar.com'],
  'rtd:scope3': ['scope3.com'],
  'rtd:semantiq': ['adnz.co', 'audienzz.com'],
  'rtd:SirdataRTDModule': ['sirdata.eu', 'sirdata.io'],
  'rtd:stackupRtd': ['stackup-ai.com'],
  'rtd:weborama': ['weborama.fr'],
  'rtd:wurfl': ['wurflcloud.com'],
  'userId:33acrossId': ['33across.com'],
  'userId:abtshieldId': ['abtshield.com'],
  'userId:acxiomRealId': ['gcprivacy.id'],
  'userId:admixerId': ['admixer.com', 'admixer.net'],
  'userId:adplusId': ['ad-plus.com.tr'],
  'userId:adriverId': ['adriver.ru'],
  'userId:adtelligent': ['adtelligent.com'],
  'userId:amxId': ['a-mo.net', 'a-mx.com'],
  'userId:ceeId': ['ceeid.eu', 'wp.pl'],
  'userId:connectId': ['yahoo.com'],
  'userId:criteo': ['criteo.com'],
  'userId:czechAdId': ['cpex.cz'],
  'userId:dacId': ['impact-ad.jp'],
  'userId:euid': ['euid.eu'],
  'userId:fabrickId': ['agkn.com'],
  'userId:gemiusId': ['gemius.com'],
  'userId:hadronId': ['ad.gt'],
  'userId:id5Id': ['id5-sync.com'],
  'userId:identityLink': ['rlcdn.com'],
  'userId:intentIqId': ['geeksforgeeks.org', 'intentiq.com'],
  'userId:jixieId': ['jixie.io'],
  'userId:justId': ['audience-solutions.com'],
  'userId:kpuid': ['knsso.com'],
  'userId:liveIntentId': ['liadm.com'],
  'userId:locId': ['apache.org'],
  'userId:locid': ['apache.org'],
  'userId:lockrAIMId': ['loc.kr'],
  'userId:lotamePanoramaId': ['crwdcntrl.net'],
  'userId:merkleId': ['rkdms.com'],
  'userId:mobkoiId': ['mobkoi.com', 'smartadserver.com'],
  'userId:mwOpenLinkId': ['mediawallahscript.com'],
  'userId:mygaruId': ['mygaru.com'],
  'userId:naveggId': ['navegg.com'],
  'userId:novatiq': ['novatiq.com', 'spadsync.com'],
  'userId:operaId': ['opera.com'],
  'userId:permutiveIdentityManagerId': ['permutive.app'],
  'userId:publinkId': ['dotomi.com'],
  'userId:pubmaticId': ['pubmatic.com'],
  'userId:qid': ['adquery.io'],
  'userId:startioId': ['startappnetwork.com', 'startappservice.com'],
  'userId:taboolaId': ['taboola.com'],
  'userId:tapadId': ['tapad.com'],
  'userId:teadsId': ['teads.tv'],
  'userId:tncId': ['tncid.app'],
  'userId:uid2': ['uidapi.com'],
  'userId:unifiedId': ['adsrvr.org'],
  'userId:zeotapIdPlus': ['rqtrk.eu'],
};
